name: grow_castle_calculator_next
description: "A tool for mobile game Grow Castle."
publish_to: 'none'
version: 1.7.0+1

environment:
  sdk: ">=3.13.5"
  flutter: ">=3.47.6"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^2.0.0
  get_it: ^9.3.0
  hive_flutter: ^1.1.0
  intl: ^0.20.3
  flutter_displaymode: ^0.7.0
  flutter_native_splash: ^2.4.8
  http: ^1.6.0
  dio: ^5.11.1
  package_info_plus: ^10.2.1
  path_provider: ^2.1.6
  url_launcher: ^6.3.2
  fl_chart: ^1.2.0
  material_ui: ^1.5.0
  dynamic_color: ^2.1.0
  measure_size: ^5.0.2
  flutter_markdown_plus: ^1.0.12
  file_picker: ^13.1.0
  webdav_client_plus: ^2.0.0
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.12.0
  flutter_riverpod: ^3.4.3
  riverpod_annotation: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  riverpod_generator: ^4.0.9

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_icon.png
  color_dark: "#121212"
