name: grow_castle_calculator_next
description: "A tool for mobile game Grow Castle."
publish_to: 'none'
version: 1.5.2+1

environment:
  sdk: ">=3.13.1"
  flutter: ">=3.47.1"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^9.2.1
  hive_flutter: ^1.1.0
  flutter_displaymode: ^0.7.0
  flutter_native_splash: ^2.4.8
  http: ^1.6.0
  package_info_plus: ^10.2.1
  path_provider: ^2.1.6
  url_launcher: ^6.3.2
  fl_chart: ^1.1.1
  material_ui: ^1.1.0
  dynamic_color: ^2.1.0
  measure_size: ^5.0.2
  flutter_markdown_plus: ^1.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_icon.png
  color_dark: "#121212"
